# TECHNICAL METADATA
group=com.einent

# BUILD SETTINGS
java_version=25

# HYTALE PATH MAPPING
hytale_patchline=release

org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Common
java_version                         = 25
hytale_version                       = 0.+
manifestServerVersion                = >=0.6.0 <0.7.0

# Publishing
modtale_uuid                         = 
modifold_id                          = 
curseforgeID                         = 

# Mod options
group                                = com.einent.veinmining
manifest_group                       = EineNT
mod_name                             = VeinMining
main_class                           = com.einent.veinmining.VeinMiningPlugin
mod_author                           = EineNT
mod_id                               = VeinMining
mod_license                          = MIT
mod_description                      = Instantly mine connected ores and blocks by holding the Walk key (LEFT ALT). /veinmining to configure.
mod_credits                          = EineNT, Riprod
mod_logo                             = icon-256.png
mod_url                              = https://www.curseforge.com/hytale/mods/veinmining
mod_issues                           = https://github.com/aaronpostels/veinmining/issues
mod_sources                          = https://github.com/aaronpostels/veinmining
version                              = 2.4.0
includes_pack                        = true
disabled_by_default                  = false
patchline                            = release
load_user_mods                       = false
manifest_dependencies                = 
manifest_opt_dependencies            = 